import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul className="flex gap-4 items-center justify-center bg-white text-black">
            <li>HOME</li>
            <li>About</li>
          </ul>
        </nav>
        <div className="bg-blue-900 min-h-screen">{children}</div>
        </body>
    </html>
  )
}
